#!/usr/bin/env bash

set -e

# macOS
if [[ "$(uname -s)" = "Darwin" ]]; then
  # Homebrew
  if ! $(which brew) > /dev/null 2>&1; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  brew update
  # git
  if ! $(which git) > /dev/null 2>&1; then
    brew install git
  fi
  # install miniconda3
  if ! $(which conda) > /dev/null 2>&1; then
    brew cask install miniconda
    if [[ $? != 0 ]]; then
      echo "Installing miniconda3...failed"
      exit 2
    else
      echo "Installing miniconda3...done"
      echo export "PATH=/usr/local/miniconda3/bin:$PATH" >> $HOME/.bash_profile
    fi
  fi
  
# Ubuntu
elif [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]]; then
  sudo apt-get update
  # git
  if ! $(which git) > /dev/null 2>&1; then
    sudo apt-get install git
  fi
  # wget
  if ! $(which wget) > /dev/null 2>&1; then
    sudo apt-get install wget
  fi
  # install miniconda3
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  bash ~/miniconda.sh -b -p $HOME/miniconda
  if [[ $? != 0 ]]; then
    echo "Installing miniconda3...failed"
    exit 2
  else
    echo "Installing miniconda3...done"
    echo export PATH="$HOME/miniconda/bin:$PATH" >> $HOME/.bashrc
  fi

# Other OS
else
  echo "Only macOS and Ubuntu are supported now"
fi

# Install packages using conda
conda install jupyter numpy pandas statsmodels scipy scikit-learn matplotlib seaborn beautifulsoup4 requests
